name: smart_dispencer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_clean_architecture: ^6.0.1
  flutter_fortune_wheel: ^1.3.1
  flutter_speed_dial: ^7.0.0
  fortune_wheel_enhanced: ^0.0.4
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  social_login_buttons: ^1.0.7
  sqflite: ^2.3.3+1
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/3d/
    - assets/images/logo.png
