// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9BfF7OS50WVNCe0EcvG4npVmjoU4ljg',
    appId: '1:145042075292:web:396f99250a3f0de3c0c759',
    messagingSenderId: '145042075292',
    projectId: 'minder-3b9ba',
    authDomain: 'minder-3b9ba.firebaseapp.com',
    storageBucket: 'minder-3b9ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANqa_U4IgTSZB6ThEcpC7qCyLH9Qvftes',
    appId: '1:145042075292:android:3977a5a9393b8032c0c759',
    messagingSenderId: '145042075292',
    projectId: 'minder-3b9ba',
    storageBucket: 'minder-3b9ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg2SKbF-6ICQbKYwKi1VrYSjpyjlGKQ8s',
    appId: '1:145042075292:ios:298964920b60d4f9c0c759',
    messagingSenderId: '145042075292',
    projectId: 'minder-3b9ba',
    storageBucket: 'minder-3b9ba.firebasestorage.app',
    iosBundleId: 'com.example.smartDispencer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg2SKbF-6ICQbKYwKi1VrYSjpyjlGKQ8s',
    appId: '1:145042075292:ios:298964920b60d4f9c0c759',
    messagingSenderId: '145042075292',
    projectId: 'minder-3b9ba',
    storageBucket: 'minder-3b9ba.firebasestorage.app',
    iosBundleId: 'com.example.smartDispencer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU9BfF7OS50WVNCe0EcvG4npVmjoU4ljg',
    appId: '1:145042075292:web:615b7ae24b4f47e0c0c759',
    messagingSenderId: '145042075292',
    projectId: 'minder-3b9ba',
    authDomain: 'minder-3b9ba.firebaseapp.com',
    storageBucket: 'minder-3b9ba.firebasestorage.app',
  );
}
